### ISSUE TITLE
Error using spreadsheet exporter

### ISSUE THREAD

**Issue by shabnam-b** [korpling/pepperModules-SpreadsheetModules#12]
Hello,

Thank you very much for adding spreadsheet exporter!
I've used it on a corpus (exmaralda to spreadsheet), and most of the files are ok, however, with some of them I get the following error:

_[Fatal Error] :252:30: The entity name must immediately follow the '&' in the entity reference.
 [Fatal Error] 1023_0108641.exb:252:30: The entity name must immediately follow the '&' in the entity reference. Cannot map 'salt:/0/german/1023_0108641' with module 'EXMARaLDAImporter', because of a mapping result was 'FAILED'.
.
.
._

Looking at the file causing the problem, the content of a cell is the token "&"...for example in one of the files, it seems like the following line is causing the error:

`"<event start="T9" end="T10">&</event>"`

Is there a way to avoid this error without changing the content of all those files?

Thanks!

**Comment by amir-zeldes** [comment]
Hi @shabnam-b - I think this is basically not an error in the SpreadsheetModules. It sounds like the part that's failing is the EXMARaLDAImporter, but I also wouldn't call it a bug exactly, since EXMARaLDA is an XML format, and XML requires plain ampersands to be escaped as `&amp;`. If the XML parser sees a "&" without a following alphanumeric entity identifier ending in ";" the importer fails because the input is not well-formed XML.

The easiest solution IMO is to just pre-process the EXMARaLDA files by replacing any element contents with "&" (or "<" or ">", which are also not allowed) with the appropriate XML escapes. If you're in contact with the corpus creators, it might also be good to let them know there is a bug in the data.
